### ISSUE TITLE
Plots currently display a future date (2024)

### ISSUE THREAD

**Issue by sebastien-lenard** [nsidc/snow-today-webapp#54]
The website is currently displaying the message data "as of 2024/10/31".
This should be temporarily corrected by the message "as of 2023/09/21" for each region and variable.

Additional comment
I confirm that the v2023 web-app code take the day of the water year in the last file received and compute a unix date by taking the water year of today.

The modification should only concern L. 168 of script snow-today-webapp/src/components/LinePlot.tsx
      text: `As of ${ytdSeriesLastDate.toISOString().split('T')[0]}`,
which should be replaced by :
      text: `As of 2023-09-19`,
if i understand the code.

**Comment by MattF-NSIDC** [comment]
Discussion: https://nsidc.slack.com/archives/CSFNPTATX/p1698775904295259

**Comment by windnagelnsidc** [comment]
We decided to just put a message on the web site alerting users of the issue and we'll fix it when we do a new release of the app.

**Comment by mfisher87** [comment]
This is resolved in v0.16.0 (QA) of the webapp and the new snow surface properties data interface specification adopted by Sebastien (i.e., supercomputer now sends a full date instead of only DOWY)!
